# Generated by Django 3.2.25 on 2025-06-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_obraarte'),
        ('blog', '0006_publicacion'),
    ]

    operations = [
    ]
