# Generated by Django 3.2.25 on 2025-06-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_0003_obraarte_0006_publicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObraArte',
        ),
    ]
