# Generated by Django 3.2.25 on 2025-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_obraarte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paises',
            name='libros',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='paises',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
