# Generated by Django 3.2.25 on 2025-06-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250625_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
